### PR TITLE
Fable 1.1 Support - Round 2

### PR DESCRIPTION
**Pull request by mizzle-mo**
Initial try at 1.1 Support
* I removed the paket.references referring to NUnit as I am not sure what to do with it.  The following errors need to be resolved still.
* The test project is not currently connected to anything as I am not familiar with NUnit.

ERROR in ./src/thegamma/monaco.fs
Module not found: Error: Can't resolve 'monaco' in '/Users/mike/Code/thegamma-temp/src/thegamma'
 @ ./src/thegamma/monaco.fs 15:0-43
 @ ./src/thegamma/main.fs
 @ ./thegamma-script.fsproj

ERROR in ./src/thegamma/services.fs
Module not found: Error: Can't resolve 'virtual-dom' in '/Users/mike/Code/thegamma-temp/src/thegamma'
 @ ./src/thegamma/services.fs 26:0-42
 @ ./src/thegamma/main.fs
 @ ./thegamma-script.fsproj

ERROR in ./src/libraries/html.fs
Module not found: Error: Can't resolve 'virtual-dom' in '/Users/mike/Code/thegamma-temp/src/libraries'
 @ ./src/libraries/html.fs 12:0-39
 @ ./src/libraries/tables.fs
 @ ./src/thegamma/main.fs
 @ ./thegamma-script.fsproj

ERROR in ./src/libraries/compost.fs
Module not found: Error: Can't resolve 'virtual-dom' in '/Users/mike/Code/thegamma-temp/src/libraries'
 @ ./src/libraries/compost.fs 19:0-42
 @ ./src/libraries/interactive.fs
 @ ./src/thegamma/main.fs
 @ ./thegamma-script.fsproj

### CODE REVIEW

**Comment by mizzle-mo** [comment]
I tried to do this in a better way to keep all of your git history and files intact.  My hope is that @tpetricek can take it from here as I am not intimate enough with the project to push it through to completion.

**Comment by tpetricek** [comment]
This looks great! Will try to take it from here.

How do I run this? I used to have `npm run watch` which started Fable in background and watched for changes. Then I had other projects and used `npm link thegamma-script` so that they always run against the current version.

What good workflow can replace this?

**Comment by alfonsogarciacaro** [comment]
Thanks for this @mike-morr.

@tpetricek you should be able to keep the same workflow changing the commands slightly, I'll have a look later this week when I'm back home :+1:

**Comment by tpetricek** [comment]
@alfonsogarciacaro Thanks, sounds good! Let me see if we can figure this out without your help first. I opened #8 and I'll see if anyone from the wider community can help - there are some obvious things to do first. I'll ping you if I'm stuck and need the Master Wizard of Fable ;-)

**Comment by mizzle-mo** [comment]
@tpetricek Let me know if you still need help with this, running the code should be the same as any other Fable 1.1 app.  ```dotnet restore``` ```dotnet fable yarn-run start```

**Comment by tpetricek** [comment]
@mike-morr If you have time, I still need to fix the continuous integration... I think that still assumes the original format, so it does not work at the moment.

**Pull request closed without merging**
